FROM bcit/alpine:3.10
<%= snippet('labels', binding) -%>

RUN apk add --no-cache \
    git \
    rsync \
    php7=<%= image.vars['php_apk_version'] -%>
<% image.vars['php_extensions'].each do |ext| -%> \
    php7-<%= ext %>=<%= image.vars['php_apk_version'] -%>
<% end -%>
<% image.vars['php_pecl'].each do |ext| -%> \
    php7-pecl-<%= ext -%>
<% end %>

RUN sed -i "s/;error_log = log\/php7\/error.log/error_log = \/dev\/stderr/" /etc/php7/php-fpm.conf
COPY php-fpm-www.conf /etc/php7/php-fpm.d/www.conf
RUN chmod 775 -R /etc/php7/

COPY 50-copy-php-fpm-config.sh /docker-entrypoint.d/

WORKDIR "/application"
EXPOSE 9000
CMD ["/usr/sbin/php-fpm7", "-F", "-O", "-y", "/etc/php7/php-fpm.conf"]
