FROM bcit/alpine:<%= image.vars['alpine_version'] %>-latest

ENV HOME /application

<%= snippet('labels', binding) -%>

RUN apk add --no-cache \
    curl \
    git \
    rsync \
    wget \
    php<%= image.vars['php_maj_ver'] -%>=<%= image.vars['php_apk_version'] -%>
<% image.vars['php_extensions'].each do |ext| -%> \
    php<%= image.vars['php_maj_ver'] -%>-<%= ext %>=<%= image.vars['php_apk_version'] -%>
<% end -%>
<% image.vars['php_pecl'].each do |ext| -%> \
    php<%= image.vars['php_maj_ver'] -%>-pecl-<%= ext -%>
<% end %>

RUN pear<%= image.vars['php_maj_ver'] %> channel-update pear.php.net && pear<%= image.vars['php_maj_ver'] %> install <% -%>
<% image.vars['php_pear'].each do |ext| -%> \
    <%= ext -%>
<% end %>

<% if image.variant == 'debug' -%>
RUN apk add --no-cache \
    php<%= image.vars['php_maj_ver'] -%>=<%= image.vars['php_apk_version'] -%>
<% image.vars['php_debug_extensions'].each do |ext| -%> \
    php<%= image.vars['php_maj_ver'] -%>-<%= ext %>=<%= image.vars['php_apk_version'] -%>
<% end -%>
<% image.vars['php_debug_pecl'].each do |ext| -%> \
    php<%= image.vars['php_maj_ver'] -%>-pecl-<%= ext -%>
<% end -%>

<% end -%>

COPY --from=composer /usr/bin/composer /usr/bin/composer
<% if image.vars['php_maj_ver'] == '8' -%>
RUN ln -s /usr/bin/php8 /usr/bin/php
<% end -%>

RUN sed -i "s/;error_log = log\/php<%= image.vars['php_maj_ver'] -%>\/error.log/error_log = \/dev\/stderr/" /etc/php<%= image.vars['php_maj_ver'] -%>/php-fpm.conf
COPY php-fpm-www.conf /etc/php<%= image.vars['php_maj_ver'] -%>/php-fpm.d/www.conf
RUN chmod 775 -R /etc/php<%= image.vars['php_maj_ver'] -%>/

COPY 50-copy-php-fpm-config.sh /docker-entrypoint.d/

RUN mkdir -p /application \
 && chown 0:0 /application \
 && chmod 775 /application

WORKDIR /application
EXPOSE 9000
CMD ["/usr/sbin/php-fpm<%= image.vars['php_maj_ver'] -%>", "-F", "-O", "-y", "/etc/php<%= image.vars['php_maj_ver'] -%>/php-fpm.conf"]
